### ISSUE TITLE
Compatibility with nextjs 9.5

### ISSUE THREAD

**Issue by gitmonster** [stuart-williams/next-instantsearch#3]
**Describe the bug**
Thank you for your hard work. While this lib works flawlessly with nextjs 9.4.4 I've got problems using the new 9.5 release. 

**To Reproduce**
See the following stack trace:

28.7.2020 08:39:06TypeError: Cannot read property 'pathname' of null
28.7.2020 08:39:06    at Link (/app/node_modules/@my/project/.next/server/pages/[language]/calendars/[year]/[month]/[genre].js:3285:14)
28.7.2020 08:39:06    at d (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
28.7.2020 08:39:06    at $a (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
28.7.2020 08:39:06    at a.b.render (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
28.7.2020 08:39:06    at a.b.read (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
28.7.2020 08:39:06    at renderToString (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
28.7.2020 08:39:06    at Object.findResultsState (/app/node_modules/react-instantsearch-dom/dist/cjs/core/createInstantSearchServer.js:148:30)
28.7.2020 08:39:06    at /app/node_modules/next-instantsearch/build/with-instantsearch.js:112:51
28.7.2020 08:39:06    at step (/app/node_modules/next-instantsearch/build/with-instantsearch.js:63:23)
28.7.2020 08:39:06    at Object.next (/app/node_modules/next-instantsearch/build/with-instantsearch.js:44:53)

**Expected behavior**
To be compatible with nextjs 9.5.

**Screenshots**
nop

**Desktop (please complete the following information):**
 - OS: linux
 - Browser: chrome

**Comment by stuart-williams** [comment]
Apologies for the late reply @gitmonster and I appreciate this may no longer be an issue but I've just upgraded the example to Next v10 and all seems fine.

**Comment by gitmonster** [comment]
thanks for the commit.
